# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and merge dev into master

on:
  push:
    branches: [ dev ]

jobs:
  build-merge:

    runs-on: ubuntu-latest

    steps:
      # Setup Python
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Run Python Script
      - name: Colombia Covid19 Pipeline
        env:
          DATA_WRAPPER_TOKEN: ${{ secrets.DATA_WRAPPER_TOKEN }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          # Run Colombia Covid19 Pipeline
          ./run.sh
          # Update Chart Colombia Covid19 Time Line
          curl --request GET --url 'https://api.datawrapper.de/v3/charts/b9YVt/export/png?unit=px&mode=rgb&plain=false&scale=2&borderWidth=20' --header "Authorization: Bearer $DATA_WRAPPER_TOKEN" --header 'accept: */*' --output './chart/covid19co_time_line.png'
      # Setup Merge to master branch
      - uses: actions/checkout@master
      - name: Merge to master branch
        if: success()
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
