# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Schedule master

on:
  #push:
  #  branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  schedule:

    runs-on: ubuntu-latest

    steps:
      # Setup Python
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Run Python Script
      - name: Colombia Covid 19 Pipeline Schedule
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DATA_WRAPPER_TOKEN: ${{ secrets.DATA_WRAPPER_TOKEN }}
        run: |
          # Run Colombia Covid 19 Pipeline Schedule
          ./run.sh
          # Check any change
          if [[ $(git status --porcelain) ]]; then
              # Update Chart Colombia Covid19 Time Line
              curl --request GET --url 'https://api.datawrapper.de/v3/charts/b9YVt/export/png?unit=px&mode=rgb&plain=false&scale=2&borderWidth=20' --header "Authorization: Bearer $DATA_WRAPPER_TOKEN" --header 'accept: */*' --output './chart/covid19_time_line.png'
              echo ""
              echo 'Colombia Covid 19 Datasets Updated'
              git config --global user.email 'sebaxtianrioss@gmail.com'
              git config --global user.name 'Sebastian Rios Sabogal'
              git add .
              git commit -m "Updated at $(date)"
              git push origin master
              # Create new release
              ./release.sh
          else
              echo 'Not Changes'
          fi
